// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8SJ71CycYeXCpcQd9GG23gDOdRp1DMLU',
    appId: '1:174446410133:web:35e68e2b866bbb2e89de9c',
    messagingSenderId: '174446410133',
    projectId: 'northguide-bb031',
    authDomain: 'northguide-bb031.firebaseapp.com',
    storageBucket: 'northguide-bb031.firebasestorage.app',
    measurementId: 'G-GE6NNQ41L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCnJjaq1ZFaHjIyWNLhhBhQTi2BlAJXtM',
    appId: '1:174446410133:android:1fbb63f60ba641bb89de9c',
    messagingSenderId: '174446410133',
    projectId: 'northguide-bb031',
    storageBucket: 'northguide-bb031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe1X5405gHfWLjhV3pLqKWHqCIOrs2ThQ',
    appId: '1:174446410133:ios:6620d72ff02759e389de9c',
    messagingSenderId: '174446410133',
    projectId: 'northguide-bb031',
    storageBucket: 'northguide-bb031.firebasestorage.app',
    iosBundleId: 'com.example.dalilekFiAlshamal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe1X5405gHfWLjhV3pLqKWHqCIOrs2ThQ',
    appId: '1:174446410133:ios:6620d72ff02759e389de9c',
    messagingSenderId: '174446410133',
    projectId: 'northguide-bb031',
    storageBucket: 'northguide-bb031.firebasestorage.app',
    iosBundleId: 'com.example.dalilekFiAlshamal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8SJ71CycYeXCpcQd9GG23gDOdRp1DMLU',
    appId: '1:174446410133:web:cf40a5f6832d13c289de9c',
    messagingSenderId: '174446410133',
    projectId: 'northguide-bb031',
    authDomain: 'northguide-bb031.firebaseapp.com',
    storageBucket: 'northguide-bb031.firebasestorage.app',
    measurementId: 'G-NTTVSQ3SHY',
  );
}
